### ISSUE TITLE
Implement love.physics

### ISSUE THREAD

**Issue by cklidify** [VideahGams/LovePotion#10]
I'd love to use physics in my game but sadly I can't because LovePotion doesn't support it :cry: 

If you could add support for love.physics sometime soon that'd be great

**Comment by PremadeGames** [comment]
I second this.. the lack of love.physics is hindering me pretty much..

**Comment by VideahGams** [comment]
Very unlikely considering the sheer size and complexity of love.physics.
I don't even know if Box2D would work on 3DS or not.

Depending on what you want to do, please consider the text on love.physics's wiki page.
```
love.physics is not lightweight, and not even remotely simple to use. 
It's a ten-ton hammer designed for heavy-lifting (er...hammer...lifting?)
If you are just trying to make a character jump around on blocks or the likes, 
then move along, nothing to see here.
```
