### ISSUE TITLE
Love.filesystem

### ISSUE THREAD

**Issue by cklidify** [VideahGams/LovePotion#12]
I want to use Tiled to make my maps for my LovePotion games but I can't due to love.filesystem not being supported with LovePotion. I was wondering if this could be done, and if so, when will it be done?

**Comment by VideahGams** [comment]
love.filesystem is on my ToDo list at the moment.

As for getting Tiled maps working you'll probably have to wait a bit as [STI](https://github.com/karai17/Simple-Tiled-Implementation) doesn't currently work on LovePotion (yet) because Canvases and SpriteBatches aren't implemented yet.

**Comment by TurtleP** [comment]
I myself am trying my hand at love.filesystem, but there's no eta or anything. I have to do some research. Mainly I need to find out how to get the current application path, since it won't always be "LovePotion/".

**Comment by s3r1alpari4h** [comment]
The Homebrew usually starts in the Homebrew path (afaik, I don't even have a 3ds to test on atm) so you might be able to use something like

```
#include <unistd.h>
#include <stdio.h>

int main() {
char cwd[1024];
if (getcwd(cwd, sizeof(cwd)) == NULL) printf("Error getting current directory.\n");
return 0;
}
```

**Comment by CereEnder** [comment]
Any news about filesystem?

**Comment by TurtleP** [comment]
It's been added, but Videah hasn't been keeping the repo up to date. The current build does have file system.

**Comment by CereEnder** [comment]
Thank you  turtleP! Then I have to build it by myself? Love your work!

**Comment by TurtleP** [comment]
@CereEnder I'll be pushing a newer build to this repo soon:tm:. It'll include some changes to audio and whatnot, but I'll make a separate issue as a 'to-do' or roadmap type thing.
