### ISSUE TITLE
getPowerInfo() during charging returns "battery"

### ISSUE THREAD

**Issue by TurtleP** [VideahGams/LovePotion#13]
Very minor, just wanted to point it out since you never did test it (as read in comments, but you may have actually tested it i dunno..) but it's just there.

**Comment by VideahGams** [comment]
PR #25 should have fixed this.

**Comment by Substance12** [comment]
It does work but it returns "battery" when it's 100% charged. I'm not sure if it's how it should work but I have an idea to fix it easily.
