### ISSUE TITLE
Ninjhax 2.5 Tweaks Needed

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#16]
With 2.5 out, a few problems have arised.
The following are the issues that are known, whether or not it's my or smeas fault I don't know.

 * Performance Hit (Other homebrew apps are facing this issue aswell), usual framerate almost halved
 * Crash on exit (Causes the 3DS to freeze when it tries to return to the launcher)
 * csnd is deprecated, needs to be replaced with dsp

**Comment by Substance12** [comment]
Have the first two issues been fixed? I get a constant 60 FPS on my game which has quite a lot of code and i've never experienced a crash on exit.

**Comment by VideahGams** [comment]
The performance hit isn't as bad now due to the N3DS speed up, but it's still not as good as it was

The crashing is semi-random and needs more looking into

Still need to rework the audio system to use DSP

**Comment by VideahGams** [comment]
e72ab0679562ab2c92f55b2faced3d197b3a94f3 reworked love.audio with DSP, closing this issue.
