### ISSUE TITLE
"love.createhandlers" is not included (workaround inside)

### ISSUE THREAD

**Issue by Substance12** [VideahGams/LovePotion#19]
While making my game I ran into this issue. I wanted to use the HUMP gamestate library to use game states in it. However, it required the function love.createhandlers and it wasn't anywhere in the LÖVEPotion code. I'm not sure how crucial that function is for the engine, but it's required to make the library work.

I was able to get it working by copy-pasting the function from the LÖVE source code, putting it in a file calling it at the end and using dofile at the very beginning of main.lua. I'm pretty sure there is a less messy way to do it, though.

The file is included below.

[hotfix.zip](https://github.com/VideahGams/LovePotion/files/60668/hotfix.zip)

**Comment by VideahGams** [comment]
I'm currently on vacation with nothing but a phone, so I'll check this out when I get back in the 18th

**Comment by Substance12** [comment]
Okay, no worries

**Comment by VideahGams** [comment]
Should be fixed in d3e9883429d9d444281461ddf8de0032045e7948.
