### ISSUE TITLE
Update to latest ctrulib

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#21]
ctrulib refactor is out and this requires updating most of xerpi's libs.

**Comment by Substance12** [comment]
I'm willing to help with this. Here are the changes for sf2dlib and sftdlib from like 9 days ago, just after the ctrulib refactor:

https://github.com/xerpi/sf2dlib/commit/b84802a6f2965809ff6db2f403face5c64d17cca
https://github.com/xerpi/sftdlib/commit/50c5f1c7d9158917d0d47770b4d7c85338118aff

sfillib remains unchanged.

**Comment by Substance12** [comment]
I'll also try changing your files but I can't promise anything since I haven't been able to compile freetype yet.

**Comment by Substance12** [comment]
Sorry for that pull request, i'm still trying to figure github out. The build doesn't pass because i've only fixed one file, there is still a lot more that's wrong.
