### ISSUE TITLE
Speedup when staying on sleep mode for a while?

### ISSUE THREAD

**Issue by Substance12** [VideahGams/LovePotion#22]
I can't confirm this but I left my game on sleep mode and when I opened it, an animation was running like twice as fast. Can anyone else test if love.timer.getDelta() gets bugged like this?

**Comment by Ranguna** [comment]
I belive this is a "normal" behavior of love itself. 
On your pc if you hold the window down for a while, the game will stop updating it's draw call and once you release the window, the game will speed for for a second. 
Your best bet is to limit dt at the start of your love.update function like this :
''' lua
dt = dt >  1/20 and 1/20 or dt
'''
This will set dt to a minimum of 1/20 seconds.

**Comment by TurtleP** [comment]
Yeah, I know this is old, but do what Ranguna suggested. I usually do:

```lua
dt = math.min(1/60, dt)
```
