### ISSUE TITLE
Error on load images

### ISSUE THREAD

**Issue by son-link** [VideahGams/LovePotion#28]
Hi, firts sorry for my english
I compile the last commit and test my game on my old 3DS and Citra emu. I comment functions on mi game and the error is on love.graphics.newImage(). Work fine on before versions (i don't remember the exact commit)
I compiled with the last Citrus revisión, sf2dlib,3ds_portlibs, etc.

This is the make output: https://gist.github.com/son-link/d2fe18721d1b1711eed9

I use this repo for the 3ds_portlibs: https://github.com/devkitPro/3ds_portlibs

**Comment by Substance12** [comment]
You have to use these portlibs.

https://github.com/cpp3ds/3ds_portlibs

**Comment by VideahGams** [comment]
Try using the portlibs @Substance12 linked

**Comment by Substance12** [comment]
Also, are you using stfdlib and sfilib?

**Comment by son-link** [comment]
Thanks, now works. I compile sfilib (i did not have it), recompile zlib, freetype, etc.
