### ISSUE TITLE
love.graphics.circle causes other things to not draw.

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#3]
This is an sf2dlib issue

xerpi/sf2dlib#9

**Comment by Substance12** [comment]
Is it fixed?

**Comment by VideahGams** [comment]
Not sure, possibly, I need to do some tests.

**Comment by fartingJohn** [comment]
you might know this, but you have to place the stuff you want to draw in the **right order**. for example -

*function love.draw()
      rectangleDraw() -- the rectangle is drawn on top
      circleDraw() -- the circle is drawn beneath
end*

- **i hope i helped ;)**

**Comment by VideahGams** [comment]
Fixed a while ago, forgot to close this.
