### ISSUE TITLE
CIA, 3DS builds

### ISSUE THREAD

**Issue by Substance12** [VideahGams/LovePotion#30]
These didn't work properly before so they were removed. If anyone knows how to work with CIA and 3DS building, help would be very appreciated.

**Comment by Substance12** [comment]
Now looking at how other CIA-compatible apps are built it doesn't seem so hard, but what would be a good way to handle the "game" directory?

**Comment by VideahGams** [comment]
Yeah, I'm not sure how to handle it.

How lpp-3ds does it is embed's index.lua into lpp-3ds itself and loads it from there.
However, this is only useful for 1-script projects, not a project with a ton of images/sounds/scripts etc.

**Comment by Substance12** [comment]
I was thinking that it could load the game folder from another folder in the root of the SD card that matches the application's name.

**Comment by CereEnder** [comment]
Maybe can use the lua syntax "dofile"? I didn't try it but maybe can work.

**Comment by Ryuzaki-MrL** [comment]
Is it possible to implement the use of .love files? So the cia could load the <game-title>.love file.

**Comment by VideahGams** [comment]
Added in 605502889f2d2cf883b435df10f106569db993dc to much drama, but I'll leave this issue open till I do a proper write-up about it in the readme.
