### ISSUE TITLE
Add .wav and .ogg support to love.audio + other audio features

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#4]
I've attempted to add love.audio, but it isn't working.
Will attempt again in the future.

**Comment by Mechazawa** [comment]
Has any progress been made? Is help needed?

**Comment by VideahGams** [comment]
Eh, I've put love.audio on the side for now, I have other things that need to be done that I know how to do properly. I will work on it again soon though, possibly trying to get .wav and .ogg working this time.

**Comment by VideahGams** [comment]
With the commit d31c1cdd69e2242a881d4d5594b78ff9d4c3e005 I've managed to add basic audio support using .raw files, but .wav and .ogg support will hopefully be added in the future.

**Comment by VideahGams** [comment]
Commit f5e52558c142bae72e6ca4ac0ddac85f494d4268 added .wav support, I will close this issue and open up another one for more audio features.
