### ISSUE TITLE
How to use the touch screen as a  button?

### ISSUE THREAD

**Issue by The-Sparrow** [VideahGams/LovePotion#44]
I want to make my LovePotion app do something  every time the touch screen is touched,
how would i go through with this?

**Comment by CereEnder** [comment]
well, you need to make some class button, with an X,Y,Width,and Height.

when you do a touch event you have to check if you are touching this button.

if love.mousePressed() then
  local posx, post = love.mouse.getPosition()

**Comment by CereEnder** [comment]
well, you need to make some class button, with an X,Y,Width,and Height.

when you do a touch event you have to check if you are touching this button.
You have love.mouse.mouseisDown or love.mouse.mousepressed callback for doing this.

**Comment by The-Sparrow** [comment]
Okay thanks!
