### ISSUE TITLE
LuaJIT(?)

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#5]
Replacing the version of Lua we currently have (Lua 5.1 with lua-compat-5.2) with LuaJIT would be nice, seeing as that's the version LÖVE uses.

I have no idea if JIT compilation would work or not though.

**Comment by TurtleP** [comment]
Well, all I can see is from http://luajit.org/luajit.html that it's written in C like Lua (seemed to be obvious :v) but all we can do is try, right?

**Comment by VideahGams** [comment]
It's probably not possible because LuaJIT's interpreter is rewritten in assembly, but I will leave this open as a hopeful dream

**Comment by TurtleP** [comment]
@VideahGams you've attempted it over the past while, and might not be worth porting it ourselves atm. I'll close it for now, but if it manages to be done by someone else that'd be awesome.
