### ISSUE TITLE
Button Presses not working correctly

### ISSUE THREAD

**Issue by Xavyrr** [VideahGams/LovePotion#55]
Remember on the GBAtemp thread I described the issue of booleans not working and/or button presses not being evaluated correctly? It seems to in fact be the button presses not working right.
I made that to confirm the issue, a timer goes up every frame that the A, B and DPad-Down is pressed,
when run on my 3DS, the number shoots to the hundreds within seconds with no buttons being pressed.
Here is the main.lua http://puu.sh/nT28e/5a87281480.lua
I think this is why my LOVE project hits a linear allocation error: It keeps loading everything because it's non-stop loading and exiting states due to the input, which would explain why the project runs fine on the last official release. :D

**Comment by VideahGams** [comment]
Should be fixed in 3dd3c2789765415795b412ba5bede3b2f16a1d86 (wow that was easy)

**Comment by Xavyrr** [comment]
If this lets my game run, I want you to know I löve you lol.

**Comment by Xavyrr** [comment]
Okay! Aside from audio issues (music not staring once and looping, instead loading twice and looping over itself lol) It works! Thanks!
