### ISSUE TITLE
Audio sources not working with CIA version

### ISSUE THREAD

**Issue by Xavyrr** [VideahGams/LovePotion#57]
Attempting to use audio sources on CIA builds of LP throw an error, 'attemp to index field 'source' (a nil value)'. This only happens when trying to do things like source:play or source:setLooping, no error occurs when defining the source as far as I can tell (but that might be where the issue is since it is a nil value). This does not happen with homebrew/3dsx versions. (O3DS A9LH 10.7U)

**Comment by MerryMage** [comment]
Not a dev of LovePotion, but: 

ctrulib has two methods to get at a DSP firmware to upload to the DSP (audio coprocessor):

1. Asking the homebrew menu to give it one
2. Looking in `sdmc:/3ds/dspfirm.cdc`

I would recommend dumping your DSP firmware if you want the CIA version to work.

**Comment by Substance12** [comment]
Yeah, try dumping your DSP with this:

https://gbatemp.net/threads/release-dsp-firmware-dumper.402108/

**Comment by Xavyrr** [comment]
Weird, I thought I replied to this already... But yeah that did the trick. This can be marked as not a big since it's just a caveat of using homebrew CIAs. Thanks a ton!
