### ISSUE TITLE
Code error on latest build, runs fine older build

### ISSUE THREAD

**Issue by Xavyrr** [VideahGams/LovePotion#65]
I finally updated to the latest version of LP, along with updating all of my libraries. However, running my code throws an error for a missing closing brace, when I have looked over it for about an hour, and the exact same code runs fine on my older build. Unfortunately I can't seem to isolate it, so I included both versions of LovePotion, and the game folder. I'll keep looking into it, but not tonight since it's kinda making me frustrated lol. Thanks in advanced.

[old_build.zip](https://github.com/VideahGams/LovePotion/files/494441/old_build.zip)
[new_build.zip](https://github.com/VideahGams/LovePotion/files/494442/new_build.zip)
[game.zip](https://github.com/VideahGams/LovePotion/files/494443/game.zip)

**Comment by VideahGams** [comment]
Alright, I'll look into it tonight

**Comment by TurtleP** [comment]
Xavyrr, I'll try to get some of my latest work in when I can. It'll have audio streaming for Ogg Vorbis, but not wave. This build should be fine when I push it (hence the fact I'm making sure it passes builds while working :P ).
