### ISSUE TITLE
Can I get a nightly release? pleeeaaaaase?

### ISSUE THREAD

**Issue by miltoncandelero** [VideahGams/LovePotion#67]
Hi there. I'm working on a game for the global game jam and I'm having problem with the scale of the sprites and deltatime sometimes not working at all.

I've seen that you fixed this in newer commits but I can not compile the code for my life.

I keep getting troubles trying to get freetype to make itself to I can compile the code.

The latest working release (acording to the bot) is this: https://github.com/VideahGams/LovePotion/tree/de360cad1e87906053a9e636c7e9e82886440cd3

I know this is an awful thing to do, but I am kinda desperate 😓 

Thank you for your time and efforts!

**Comment by PremadeGames** [comment]
Were you able to build LovePotion successfully? I tried compiling a few weeks ago and failed

**Comment by miltoncandelero** [comment]
I didn't use the master. I used the last release that Travis could build and had to replace a lot of the 2d libs and fix the makefile to use citro3d.

But I managed to do it. (and the sprite scale wasn’t fixed LOL)
