### ISSUE TITLE
Can't use tables in love.graphics.setColor

### ISSUE THREAD

**Issue by cklidify** [VideahGams/LovePotion#9]
For example, I can't do love.graphics.setColor(zones[o].color)

But in actual LOVE2D, I can...

If this could be fixed in a future version that would be amazing :D

EDIT: Error says "Expected integer, got table"

**Comment by VideahGams** [comment]
Yeah, I hope to fix this soon. In the mean time just use the unpack function like this
```lua
colorTable = {255, 155, 0}
love.graphics.setColor(unpack(colorTable))
```

**Comment by cklidify** [comment]
Alright, thanks!

**Comment by VideahGams** [comment]
2a5f4464d7fd45e9dfa0ddedbc16c0a443887c0c fixes this.
